yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  "@chakra-ui/icons@*":
      peerDependencies:
        framer-motion: "2.x"
        react: "16.x || 17.x"
        react-dom: "16.x || 17.x"
        "@emotion/react": "^11.0.0"
        "@emotion/styled": "^11.0.0"
  "@chakra-ui/accordion@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/alert@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/avatar@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/breadcrumb@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/button@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/checkbox@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/clickable@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/close-button@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/color-mode@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/control-box@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/counter@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/css@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/descendant@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/editable@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/focus-lock@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/form-control@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/hooks@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/icon@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/image@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/input@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/layout@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/live-region@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/media-query@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/menu@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/modal@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/number-input@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/pin-input@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/popover@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/popper@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/portal@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/progress@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/radio@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/react@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/select@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/skeleton@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
      "@chakra-ui/theme": ">=1.0.0"
  "@chakra-ui/slider@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/spinner@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/stat@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/styled-system@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/switch@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/system@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/table@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/tabs@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/tag@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/textarea@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/theme-tools@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/theme@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/toast@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/tooltip@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/transition@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/utils@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"
  "@chakra-ui/visually-hidden@*":
    peerDependencies:
      framer-motion: "2.x"
      react: "16.x || 17.x"
      react-dom: "16.x || 17.x"
      "@emotion/react": "^11.0.0"
      "@emotion/styled": "^11.0.0"